### ISSUE TITLE
Autocompleter range

### ISSUE THREAD

**Issue by dominch** [staskie/simple_author_change#11] opened 2015-10-16 14:38 UTC
When I'm editing author it loads all users from Redmine (sorted by ID what makes very difficult to seek for specific one) and when I'm using autocompleter it finds only users from project (and this is not enough - I want to assign somebody from other project). 

BTW: pressing enter in autocompleter field causes 404.

**Comment by staskie** [comment] 2015-10-20 21:12
Hi there,

Loading users from a project only is done by design. Some people requested this functionality when I developed this plugin.

Sorting and submitting by pressing enter on autocomplete form should be fixed.

**Closed by staskie** 2015-10-20 21:12 UTC

**Comment by dominch** [comment] 2015-10-21 09:32
I can understand when this can be better option, with about five instances I have one or two where users are isolated and I never need anyone out of project. With rest I have much more users and projects and this is case when not everybody is member of everything (because it's so many things!). 
Maybe the best way is to add checkbox and perform global search :)  

Right now when window pop up You get whole list, sorted by ID (what makes it very difficult to find), this gives me about 27 pages of users. Everyone thinks that autocompleter will filter from this list and they start to type - it's not working for them. Then they need to delete everything from field and use whole list (sorted by IDs). 
I think opposite to this is much more usable - first list with users from project (this is much shorter, and usually enough to assign one needed) and autocompleter from whole Redmine - maybe with additional checkbox to confirm global query. That can be universal - now when You need to change author as well as move issue to different project (with different members), right now You need to use that huge list via ids or make two changes. 

I already changed code to make better queries for my case, but I still think that this can be improved, and this is clear when You have many users. For sure it's most comfortable plugin with autocompleter instead of huge list like most of similar plugins have. 
Thanks for plugin and whole Your work :)
